FROM golang:1.24.4-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o chat-service cmd/chat-service/main.go

FROM alpine:3.20.1 AS prod
WORKDIR /app
COPY --from=build /app/chat-service /app/chat-service
EXPOSE 5000
CMD ["./chat-service"]