FROM golang:1.24.4-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o webrtc-service cmd/webrtc-service/main.go

FROM alpine:3.20.1 AS prod
WORKDIR /app
COPY --from=build /app/webrtc-service /app/webrtc-service
EXPOSE 4000
CMD ["./webrtc-service"]